change-template: '* $TITLE by @$AUTHOR in (#$NUMBER)'
no-changes-template: '* No changes from last release'
include-pre-releases: false
sort-direction: ascending
categories:
  - title: 'bug fix'
    collapse-after: 3
    labels:
      - 'bug'
  - title: 'documentation'
    collapse-after: 3
    labels:
      - 'documentation'
  - title: 'enhancement'
    collapse-after: 3
    labels:
      - 'enhancement'
  - title: 'refactoring'
    collapse-after: 3
    labels:
      - 'refactoring'

template: |
  ## What's Changed
  $CHANGES

  ## Contributors
  $CONTRIBUTORS

  $PREVIOUS_TAG
  $REPOSITORY
  $OWNER
