name-template: 'alpha'
tag-template: 'alpha'
categories:
  - title: 'Features'
    label: 'feature'
  - title: 'Bug Fixes'
    label: 'fix'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## O que foi alterado:

  $CHANGES

  ## Contribuidores

  $CONTRIBUTORS
