name-template: '$PREVIOUS_TAG'
tag-template: '$PREVIOUS_TAG'
categories:
  - title: 'Features'
    label: 'feature'
  - title: 'Bug Fixes'
    label: 'fix'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## O que foi alterado:

  $CHANGES
