name: Generate Changelog

on:
  push:
    tags:
      - '*'

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install github-changelog-generator
        run: gem install github_changelog_generator

      - name: Generate Changelog
        run: github_changelog_generator -u <username> -p <repository> --token ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md" -a
          git push
