name: Sync Labels

on:
  pull_request:
    types:
      - closed

jobs:
  labels:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Checkout code
      uses: actions/checkout@v3

    - uses: micnncim/action-label-syncer@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        manifest: .github/labels.yml
        prune: true
